#!/bin/bash
set -e
##################################################################################################################
# Author	:	Erik Dubois
# Website	:	https://www.erikdubois.be
# Website	:	https://www.arcolinux.info
# Website	:	https://www.arcolinux.com
# Website	:	https://www.arcolinuxd.com
# Website	:	https://www.arcolinuxforum.com
##################################################################################################################
#
#   DO NOT JUST RUN THIS. EXAMINE AND JUDGE. RUN AT YOUR OWN RISK.
#
##################################################################################################################

# software from standard Arch Linux repositories
# Core, Extra, Community, Multilib repositories

echo "Installing category Accessories"
#sudo pacman -S --noconfirm --needed xfburn           # Xfburn is a simple CD/DVD burning tool
#sudo pacman -S --noconfirm --needed cmatrix          # Shows the cool matrix scrolling lines in the terminal
#sudo pacman -S --noconfirm --needed plank            # Plank is meant to be the simplest dock on the planet
#sudo pacman -S --noconfirm --needed variety          # Changes the wallpaper on a regular interval
#sudo pacman -S --noconfirm --needed catfish          # File search by name and content
sudo pacman -S --noconfirm --needed galculator       # Based calculator
sudo pacman -S --noconfirm --needed gnome-screenshot # Capture the screen, a window, or an user-defined area and save the snapshot image to a file
sudo pacman -S --noconfirm --needed redshift         # Redshift adjusts the color temperature of your screen according to your surroundings
#sudo pacman -S --noconfirm --needed

echo "Installing category Development"
#sudo pacman -S --noconfirm --needed atom  # A text editor is at the core of a developer's toolbox
#sudo pacman -S --noconfirm --needed geany # Geany is a text editor using the GTK+ toolkit
#sudo pacman -S --noconfirm --needed meld  # Meld is a visual diff and merge tool
#sudo pacman -S --noconfirm --needed neovim # Vim-fork focused on extensibility and usability
#sudo pacman -S --noconfirm --needed python2-neovim python-neovim # NeoVim dependencies
# TODO: install nodejs and ruby dependencias
#sudo pacman -S --noconfirm --needed

echo "Installing category Education"
#sudo pacman -S --noconfirm --needed

echo "Installing category Games"
#sudo pacman -S --noconfirm --needed

echo "Installing category Graphics"
#sudo pacman -S --noconfirm --needed darktable         # Darktable is an open source photography workflow application and raw developer
#sudo pacman -S --noconfirm --needed gimp              # GIMP is an acronym for GNU Image Manipulation Program
#sudo pacman -S --noconfirm --needed inkscape          # Inkscape is a professional vector graphics editor
#sudo pacman -S --noconfirm --needed pinta             # Pinta is a free, open source program for drawing and image editing
sudo pacman -S --noconfirm --needed gnome-font-viewer # GNOME Fonts shows you the fonts installed on your computer
#sudo pacman -S --noconfirm --needed gpick             # Gpick is an advanced color picker and palette editing tool
sudo pacman -S --noconfirm --needed ristretto         # Ristretto is a fast and lightweight image viewer for the Xfce desktop
#sudo pacman -S --noconfirm --needed

echo "Installing category Internet"
#sudo pacman -S --noconfirm --needed chromium         # Chromium is an open-source browser project
#sudo pacman -S --noconfirm --needed filezilla        # The free FTP solution for both client and server
#sudo pacman -S --noconfirm --needed hexchat          # HexChat is an IRC client based on XChat
#sudo pacman -S --noconfirm --needed transmission-cli # Transmission is a BitTorrent client
#sudo pacman -S --noconfirm --needed transmission-gtk # Transmission is a BitTorrent client
sudo pacman -S --noconfirm --needed firefox           #
#sudo pacman -S --noconfirm --needed

echo "Installing category Multimedia"
#sudo pacman -S --noconfirm --needed clementine
#sudo pacman -S --noconfirm --needed deadbeef
#sudo pacman -S --noconfirm --needed mpv
#sudo pacman -S --noconfirm --needed openshot
sudo pacman -S --noconfirm --needed pragha
#sudo pacman -S --noconfirm --needed shotwell
sudo pacman -S --noconfirm --needed simplescreenrecorder
#sudo pacman -S --noconfirm --needed smplayer
sudo pacman -S --noconfirm --needed vlc
#sudo pacman -S --noconfirm --needed

echo "Installing category Office"

sudo pacman -S --noconfirm --needed evince
sudo pacman -S --noconfirm --needed evolution
#sudo pacman -S --noconfirm --needed geary
#sudo pacman -S --noconfirm --needed libreoffice-fresh
#sudo pacman -S --noconfirm --needed

echo "Installing category Other"

#sudo pacman -S --noconfirm --needed

echo "Installing category System"

sudo pacman -S --noconfirm --needed arc-gtk-theme
#sudo pacman -S --noconfirm --needed archey3
sudo pacman -S --noconfirm --needed baobab
#sudo pacman -S --noconfirm --needed bleachbit
sudo pacman -S --noconfirm --needed curl
sudo pacman -S --noconfirm --needed dconf-editor
sudo pacman -S --noconfirm --needed dmidecode
sudo pacman -S --noconfirm --needed ffmpegthumbnailer
sudo pacman -S --noconfirm --needed git
sudo pacman -S --noconfirm --needed glances
sudo pacman -S --noconfirm --needed gnome-disk-utility
sudo pacman -S --noconfirm --needed gnome-keyring
#sudo pacman -S --noconfirm --needed gnome-system-monitor
#sudo pacman -S --noconfirm --needed gnome-terminal
#sudo pacman -S --noconfirm --needed gnome-tweak-tool
sudo pacman -S --noconfirm --needed gparted
sudo pacman -S --noconfirm --needed grsync
sudo pacman -S --noconfirm --needed gtk-engine-murrine
sudo pacman -S --noconfirm --needed gvfs gvfs-mtp
sudo pacman -S --noconfirm --needed hardinfo
sudo pacman -S --noconfirm --needed hddtemp
sudo pacman -S --noconfirm --needed htop
sudo pacman -S --noconfirm --needed lm_sensors
sudo pacman -S --noconfirm --needed lsb-release
sudo pacman -S --noconfirm --needed mlocate
sudo pacman -S --noconfirm --needed net-tools
#sudo pacman -S --noconfirm --needed notify-osd
sudo pacman -S --noconfirm --needed noto-fonts
sudo pacman -S --noconfirm --needed numlockx
sudo pacman -S --noconfirm --needed polkit-gnome
sudo pacman -S --noconfirm --needed sane
sudo pacman -S --noconfirm --needed screenfetch
sudo pacman -S --noconfirm --needed scrot
sudo pacman -S --noconfirm --needed simple-scan
sudo pacman -S --noconfirm --needed sysstat
#sudo pacman -S --noconfirm --needed terminator
sudo pacman -S --noconfirm --needed termite
sudo pacman -S --noconfirm --needed thunar
sudo pacman -S --noconfirm --needed thunar-archive-plugin
sudo pacman -S --noconfirm --needed thunar-volman
sudo pacman -S --noconfirm --needed ttf-ubuntu-font-family
sudo pacman -S --noconfirm --needed ttf-droid
sudo pacman -S --noconfirm --needed tumbler
sudo pacman -S --noconfirm --needed vnstat
sudo pacman -S --noconfirm --needed wget
sudo pacman -S --noconfirm --needed wmctrl
sudo pacman -S --noconfirm --needed unclutter
sudo pacman -S --noconfirm --needed rxvt-unicode
sudo pacman -S --noconfirm --needed urxvt-perls
sudo pacman -S --noconfirm --needed xdg-user-dirs
sudo pacman -S --noconfirm --needed zenity
#sudo pacman -S --noconfirm --needed


###############################################################################################

# installation of zippers and unzippers
sudo pacman -S --noconfirm --needed unace unrar zip unzip sharutils  uudeview  arj cabextract file-roller

###############################################################################################


echo "################################################################"
echo "#### Software from standard Arch Linux Repo installed  #########"
echo "################################################################"
